Gopkg.lock
db/db.go
db/redis.go
models/redhat.go

Support Redis as DB back end for RedHat

Support Redis as DB back end for RedHat

---

cmd/fetch.go
cmd/notify.go
cmd/redhat.go
cmd/root.go
fetcher/redhat.go
models/redhat.go
util/util.go

Changes
- RedHat API returns array or object

Add wait and threads option

---

Gopkg.lock
db/db.go
db/redhat.go
db/redis.go

Add GetRedhatMulti

---

README.md
cmd/root.go
util/util.go

add  log-json option
`gost fetch redhat --log-json`
- stderr
```
{"lvl":"info","msg":"Fetch the list of CVEs","t":"2018-04-26T16:34:28.235895809+09:00"}
```
- logfile
```
{"lvl":"info","msg":"Fetch the list of CVEs","t":"2018-04-26T16:34:28.235895809+09:00"}
```

add log-json option

---

db/rdb.go

fix(db): no wal mode with SQLite3 backend to avoid `database is locked`

---

Gopkg.lock
Gopkg.toml
cmd/debian.go
cmd/notify.go
cmd/redhat.go
cmd/register.go
cmd/server.go
db/db.go
db/debian.go
db/rdb.go
db/redhat.go
db/redis.go
models/redhat.go
server/server.go
util/util.go

Add functions that get unfixed CVEs by distro, version and package name for RedHat and Debian.

Unfixed cves

---

db/db.go
db/microsoft.go
db/redis.go

add get multi function
fix insert productID and Name

fix(microsoft) add multi get and fix redis

---

db/redhat.go
db/redis.go

Include Affected status package in UnfixedCvesRedhat.

fix(db) Include Affected status package in UnfixedCvesRedhat

---

cmd/redhat.go
db/redhat.go
go.mod
go.sum
util/util.go

fix(util): update gorequest module #22

---

db/microsoft.go

fix(ms): queried from Microsoft CVE table #45

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docker-build.yml
.github/workflows/golangci.yml
.github/workflows/goreleaser.yml
.github/workflows/test.yml
.github/workflows/tidy.yml
cmd/notify.go
cmd/register.go
db/redis.go
fetcher/debian.go
git/git.go
server/server.go
util/redhat.go
util/util.go

Add workflows with github actions.

chore: add github actions

---

db/redhat.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef306a]
goroutine 1 [running]:
github.com/vulsio/gost/db.(*RDBDriver).GetRedhatMulti(0xc000becaa0, {0xc00097e800, 0x4d, 0xa})
/home/ubuntu/go/pkg/mod/github.com/vulsio/gost@v0.4.0/db/redhat.go:69 +0xaa
github.com/future-architect/vuls/gost.RedHat.fillCvesWithRedHatAPI({{{{0x164e3e8, 0xc000c86fc0}, {0x163a7d0, 0xc000becaa0}}}}, 0xc000252000)
/home/ubuntu/go/src/github.com/future-architect/vuls/gost/redhat.go:88 +0x24d
github.com/future-architect/vuls/gost.FillCVEsWithRedHat(0x0, {{{0x1355c22, 0x4}, {0xc00003a3d0, 0x7}, {0x0, 0x0}, {0xc000046660, 0x21}, 0x0}})
/home/ubuntu/go/src/github.com/future-architect/vuls/gost/gost.go:54 +0x173 …
```

fix(redhat): nil pointer dereference

---

cmd/debian.go
cmd/microsoft.go
cmd/notify.go
cmd/redhat.go
cmd/redhatapi.go
cmd/register.go
cmd/server.go
cmd/ubuntu.go
db/db.go
db/debian.go
db/microsoft.go
db/rdb.go
db/redhat.go
db/redis.go
db/ubuntu.go
fetcher/debian.go
fetcher/redhatapi.go
notifier/email.go
notifier/slack.go
util/util.go

refactor: remove redundant logging
make build

refactor: remove redundant logging

---

.golangci.yml
cmd/microsoft.go
db/db.go
db/microsoft.go
db/rdb.go
db/redis.go
fetcher/debian.go
fetcher/microsoft.go
fetcher/redhatapi.go
go.mod
go.sum
models/microsoft.go
models/models.go
server/server.go
util/util.go

In the case of conventional data structures, there is a possibility of mistaking a certain CVE that is modified by a different KB for each product. Fix this by making it filter by product.
The search method has also been revised to detect unfixed vulnerabilities.
The data model has been changed to a model that expresses CVSS, etc. defined for each product. 
```console
$ gost fetch microsoft
INFO[06-03|03:13:25] Initialize Database 
INFO[06-03|03:13:25] Fetched all CVEs from Microsoft 
INFO[06-03|03:13:27] Insert Microsoft CVEs into DB            db=redis
INFO[06-03|03:13:27] Inserting cves                           cves=8323
8323 / 8323 [---------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

breaking-changes(microsoft): change to a new architecture for Microsoft

---

db/redis.go
db/ubuntu.go
fetcher/microsoft.go

CVEs with deferred patches should be classified as unfixed.

feat(ubuntu): classify those with a status of deferred as unfixed

---

.github/workflows/fetch.yml
cmd/fetch.go

feat(ci): test fetch periodically

---

db/redis.go

style: fix typo

---

db/ubuntu.go

feat(ubuntu): add ubuntu 23.04

---

.golangci.yml
fetcher/redhat.go
fetcher/ubuntu.go
models/redhat.go

Fixes #134 
```console
$ gost fetch redhatapi
```

fix(fetch/redhatapi): fix RedhatEntry

---

db/ubuntu.go

add ubuntu 23.10
```console
$ gost fetch ubuntu 
INFO[10-19|01:33:30] Initialize Database 
INFO[10-19|01:33:30] Fetched                                  CVEs=45470
INFO[10-19|01:33:30] Insert Ubuntu into DB                    db=sqlite3
45470 / 45470 [------------------------------------------------] 100.00% 667 p/s
$ sqlite3 gost.sqlite3 "SELECT EXISTS(SELECT * FROM ubuntu_release_patches WHERE release_name = 'mantic')"
1
$ gost server
$ curl -s http://127.0.0.1:1325/ubuntu/2310/pkgs/linux/unfixed-cves | jq
{
"CVE-2013-7445": {
"public_date_at_usn": "1000-01-01T00:00:00Z",
"crd": "1000-01-01T00:00:00Z",
"candidate": "CVE-2013-7445",
"public_date": "2015-10-16T01:59:00Z",
"references": [
{
"reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-7445"
},
{
"reference": …
```

feat(ubuntu): add 23.10(mantic)

---

db/redis.go

There are 3,282 kernel vulnerabilities in Ubuntu.
https://ubuntu.com/security/cves?package=linux
The current implementation tries to get all vulnerabilities from Redis, consuming a huge amount of memory. This PR chunks vulnerabilities so it can mitigate the memory issue. Ideally, vulnerability detection should be processed in a streaming manner.
https://github.com/future-architect/vuls/blob/75e9883d8a8e94f73443ac3df402f26c26e07935/gost/ubuntu.go#L171-L181
The maximum memory consumption was significantly reduced from 457,120KB to 32,064KB.
```console
/usr/bin/time -f "memory(kb): %M" ./gost.master server --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
INFO[10-27|13:09:46] Starting HTTP Server... 
INFO[10-27|13:09:46] Listening                                URL=127.0.0.1:1325
____    __ …
```

refactor(db/redis): get each chunk of cve id

---

db/debian.go
db/microsoft.go
db/redhat.go
db/redis.go
db/ubuntu.go
util/util.go

no progress when --log-json option
```console
$ gost fetch debian --log-json
{"lvl":"info","msg":"Initialize Database","t":"2024-07-04T16:16:05.960068788+09:00"}
{"lvl":"info","msg":"Fetched all CVEs from Debian","t":"2024-07-04T16:16:06.00184586+09:00"}
{"CVEs":39701,"lvl":"info","msg":"Fetched","t":"2024-07-04T16:16:10.583478895+09:00"}
{"db":"sqlite3","lvl":"info","msg":"Insert Debian CVEs into DB","t":"2024-07-04T16:16:10.583537978+09:00"}
39701 / 39701 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 5215 p/s
```
```console …
```

feat(log) no progress when --log-json option

---

db/db.go
db/microsoft.go
db/redhat.go
db/redis.go
db/ubuntu.go
server/server.go

select advisories and related cve ids
```console
$ gost fetch redhat
$ gost server
$ curl http://127.0.0.1:1325/redhat/advisories | jq
{
"RHBA-2003:308": [
"CVE-2003-0961"
],
"RHBA-2004:164": [
"CVE-2004-2259"
],
"RHBA-2004:232": [
"CVE-2004-0972"
],
...
$ docker run --rm --name redis -d -p 127.0.0.1:6379:6379 redis
$ gost fetch redhat --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
$ curl http://127.0.0.1:1325/redhat/advisories | jq
{
"RHBA-2003:308": [
"CVE-2003-0961"
],
"RHBA-2004:164": [
"CVE-2004-2259"
],
"RHBA-2004:232": [
"CVE-2004-0972"
],
...
```

feat: select advisories

---

db/ubuntu.go

add 24.10
```console
$ gost fetch ubuntu
INFO[10-31|00:32:08] Initialize Database 
INFO[10-31|00:32:09] Fetched                                  CVEs=52413
INFO[10-31|00:32:09] Insert Ubuntu into DB                    db=sqlite3
52413 / 52413 [--------------------------------------------------------------------------------------] 100.00% 127 p/s
$ gost server
$ curl -s http://127.0.0.1:1325/ubuntu/2410/pkgs/linux/unfixed-cves | jq
{
"CVE-2013-7445": {
"public_date_at_usn": "1000-01-01T00:00:00Z",
"crd": "1000-01-01T00:00:00Z",
"candidate": "CVE-2013-7445",
"public_date": "2015-10-16T01:59:00Z",
"references": [
{
"reference": "https://lists.freedesktop.org/archives/dri-devel/2015-September/089778.html …
```

feat(db/ubuntu): add 24.10(oracular)

---

.github/workflows/golangci.yml
go.mod
notifier/redhat.go

build(go): update 1.24

---

fetcher/ubuntu.go

chore(fetcher/ubuntu): fix typo

---

db/ubuntu.go

add ubuntu 25.04
```console
$ gost fetch ubuntu 
$ sqlite3 gost.sqlite3 "SELECT EXISTS(SELECT * FROM ubuntu_release_patches WHERE release_name = 'plucky')"
1
$ gost server
$ curl -s http://127.0.0.1:1325/ubuntu/2504/pkgs/linux/unfixed-cves | jq
{
"CVE-2013-7445": {
"public_date_at_usn": "1000-01-01T00:00:00Z",
"crd": "1000-01-01T00:00:00Z",
"candidate": "CVE-2013-7445",
"public_date": "2015-10-16T01:59:00Z",
"references": [
{
"reference": "https://lists.freedesktop.org/archives/dri-devel/2015-September/089778.html (potential start towards fixing)"
},
{
"reference": "https://www.cve.org/CVERecord?id=CVE-2013-7445"
}
],
"description": "The Direct Rendering Manager (DRM) subsystem in the Linux kernel through 4.x mishandles requests for Graphics Execution Manager (GEM) objects, which allows …
```

feat(db/ubuntu): add 25.04(plucky)

---

models/microsoft.go

Fixes https://github.com/vulsio/gost/actions/runs/17390037232/job/49362341134
```console
$ curl -s https://raw.githubusercontent.com/vulsio/windows-vuln-feed/main/dist/vulnerability/vulnerability.json.gz | zcat | jq -r '.[] | select(.CVEID == "CVE-2020-8284")'
{
"CVEID": "CVE-2020-8284",
"Title": "A malicious server can use the FTP PASV response to trick curl 7.73.0 and earlier into connecting back to a given IP address and port and this way potentially make curl extract information about services that are otherwise private and not disclosed for example doing port scanning and service banner extractions.",
"Tag": "Mariner",
"CNA": "hackerone",
"Products": [
{
"ProductID": "19146-16820",
"Name": "cm1 curl …
```

fix!(db/microsoft): change title type from varchar(255) to text
