vulsio/gost

- cmd/redhat.go
- fetcher/redhat.go
Add `--before` option to `fetch redhat` command.
https://access.redhat.com/documentation/en-us/red_hat_security_data_api/0.1/html-single/red_hat_security_data_api/#cve
```
CVEs before the query date. [ISO 8601 is the expected format]
```
> Add before option

- cmd/debian.go
- models/debian.go
- models/redhat.go
An error occurred while fetching NVD feed with MySQL backend.
```
Error 1406: Data too long for column 'description' at row
```
Change from Varcar fixed length type to text type.
> fix(db): chagne RDB column type to text

- README.md
- cmd/server.go
- go-cve-dictionary: 1323
- goval: 1324
- gost: 1235 -> 1325
- go-exploitdb: 1326
> fix(server): change default port number to 1325 in server mode

- db/redhat.go
```EROR[09-30|05:22:05] Failed to insert.                        dbpath=/vuls/gost.sqlite3 err="Failed to parse date. date: 1999-07-25T00:00:00Z err: parsing time \"1999-07-25T00:00:00Z\": extra text: Z"
Failed to parse date. date: 1999-07-25T00:00:00Z err: parsing time "1999-07-25T00:00:00Z": extra text: Z```
> fix(redhat): failed to parse date extra text: Z

- db/db.go
- db/debian.go
- db/redis.go
- server/server.go
refs. https://github.com/future-architect/vuls/pull/1053
*Description of changes:*
In Debian, it was necessary to obtain information on Fixed CVE as well as Unfixed CVE.
I ran `gost` in server mode and confirmed that fixed and unfixed CVEs can be fetched with curl respectively.
```terminal
$ curl http://127.0.0.1:1325/debian/10/pkgs/apt/unfixed-cves | jq "."
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   924  100   924    0     0   128k      0 --:--:-- --:--:-- --:--:--  128k
{
"CVE-2011-3374": {
"ID": 4100,
"CveID": "CVE-2011-3374",
"Scope": "local",
"Description": "It was found that apt-key in apt, all versions, do not correctly validate gpg keys with the master keyring, leading to a potential …
```
> add(debian): impl GetFixedCvesDebian

- db/db.go
I removed log output of `Opening DB` and `Migrating DB`  to make it easier to see.
> remove log output of opening and removing db

- GNUmakefile
- db/debian.go
- db/redhat.go
- db/ubuntu.go
- models/models.go
- util/util.go
Change the method to evaluate ErrRecordNotFound as described in the following link.
https://gorm.io/docs/error_handling.html#ErrRecordNotFound
Also, vuln-list is now cloned to the cache dir.
> chore: change clone cache dir and error handling

- cmd/fetch.go
- cmd/microsoft.go
- cmd/notify.go
- cmd/redhatapi.go
- cmd/register.go
- cmd/root.go
- cmd/server.go
- db/redis.go
- fetcher/redhat.go
Unlike RDBs, Redis does not lose old data. For users who do not want to be affected by old data remaining, it is possible to set a timeout deadline for keys using the Redis EXPIRE command.
```console
$ redis-cli -p 6379
127.0.0.1:6379> TTL "CVE#CVE-2009-1044"
(integer) 705
127.0.0.1:6379> TTL "CVE#R#hapi-fhir-utilities"
(integer) 652
127.0.0.1:6379> TTL "CVE#D#avahi"
(integer) 491
127.0.0.1:6379> TTL "CVE#U#gnome-desktop3"
(integer) 671
127.0.0.1:6379> TTL "CVE#K#935490"
(integer) 870
127.0.0.1:6379> TTL "CVE#P#11651"
(integer) 874
127.0.0.1:6379> keys CVE#*
(empty array)
```
- https://redis.io/commands/expire
> feat(redis): add expire option

- db/microsoft.go
- db/redhat.go
- db/redis.go
```
EROR[09-18|18:03:01] Failed to HMGet.                         err="ERR wrong number of arguments for 'hmget' command"
[Sep 18 18:03:01]  INFO [localhost] jvn_vendor_product: 0 PoC are detected
[Sep 18 18:03:01]  INFO [localhost] jvn_vendor_product: 0 exploits are detected
[Sep 18 18:03:01]  INFO [localhost] pseudo type. Skip OVAL and gost detection
[Sep 18 18:03:01]  INFO [localhost] jvn_vendor_product_nover: 0 CVEs are detected with CPE
EROR[09-18|18:03:01] Failed to HMGet.                         err="ERR wrong number of arguments for 'hmget' command"
[Sep 18 18:03:01]  INFO [localhost] jvn_vendor_product_nover: 0 PoC are detected
[Sep 18 18:03:01]  INFO [localhost] jvn_vendor_product_nover: 0 exploits are detected
[Sep 18 18:03:01]  INFO [localhost] pseudo type. Skip OVAL and gost …
```
> fix: ERR wrong number of arguments for 'hmget'

- GNUmakefile
- db/db.go
- db/debian.go
- db/microsoft.go
- db/redhat.go
- db/redis.go
- db/ubuntu.go
- integration/diff_server_mode.py
- server/server.go
If `CVE==nil` in GetMicrosoftMulti in RDB, do not register it.
refs. https://github.com/vulsio/gost/pull/79
Also, GetDebianMulti and GetUbuntuMulti are implemented.
```console
$ gost server --dbtype sqlite3 --dbpath ./gost.sqlite3
$ curl -H "Content-type: application/json" -X POST -d '{"cveIDs": []}' http://127.0.0.1:1325/microsoft/multi-cves | jq . // empty CVEIDs
$ curl -H "Content-type: application/json" -X POST -d '{"cveIDs": ["CVE-0000-0000", "CVE-2021-38642"]}' http://127.0.0.1:1325/microsoft/multi-cves | jq . // contains invalid CVEID
```
> feat: fix GetMicrosoftMulti nil pointer dereference and add GetDebianMulti, GetUbuntuMulti

- cmd/debian.go
- cmd/microsoft.go
- cmd/redhat.go
- cmd/redhatapi.go
- cmd/ubuntu.go
If an error occurs during the first fetch, it is required to clean the DB during the second Insert. 
The old data can be deleted when updating between the same schema versions.
To avoid this problem, insert FetchMeta first.
> fix(db): change fetchmeta insert order

- .github/workflows/golangci.yml
- .gitignore
- .golangci.yml
- .goreleaser.yml
- .revive.toml
- GNUmakefile
- cmd/debian.go
- cmd/microsoft.go
- cmd/notify.go
- cmd/redhat.go
- cmd/redhatapi.go
- cmd/register.go
- cmd/server.go
- cmd/ubuntu.go
- db/microsoft.go
- db/rdb.go
- db/redis.go
- notifier/slack.go
- util/util.go
Change the linter to revive, since golint has been deprecated as follows.
> NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as Staticcheck and go vet should be used instead.
```console
$ make lint
$ golangci-lint run -c .golangci.yml
```
> chore(linter): change linter from golint to revive

- cmd/debian.go
- cmd/microsoft.go
- cmd/notify.go
- cmd/redhat.go
- cmd/redhatapi.go
- cmd/register.go
- cmd/server.go
- cmd/ubuntu.go
- db/rdb.go
- db/redis.go
- models/models.go
Add the time when the fetch is completed to fetchmeta.
```console
$ gost fetch debian
$ sqlite3 gost.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 10:02:31.112140894+09:00
$ gost fetch debian
$ sqlite3 gost.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 10:02:50.617469033+09:00
```
```console
$ redis-cli -p 6379
127.0.0.1:6379> HGET GOST#FETCHMETA LastFetchedAt
(nil)
$ gost fetch debian --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET GOST#FETCHMETA LastFetchedAt
"2021-12-26T10:03:23.001829261+09:00"
$ gost fetch debian --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET GOST#FETCHMETA LastFetchedAt
"2021-12-26T10:03:40.80782099+09:00"
```
You don't have to …
> feat(db): add LastFetchedDate in fetchmeta

- db/db.go
- db/redhat.go
Use the correct CPE when searching in EUS or AUS.
```console
$
```
***Is this ready for review?:*** NO
> feat(redhat): support EUS, AUS CPE scan for GetUnfixedCvesRedhat

- db/db.go
- models/ubuntu.go
Fixes #101 
When fetching ubuntu in MySQL and PostgreSQL, an error occurred because it tried to insert a string with a size larger than varchar(255). This has been fixed. Also, when fetching ubuntu with MySQL, some of the dates were `0001-01-01T00:00:00Z`, which caused the insert to fail.
In MySQL and PostgreSQL, you need to change the column type as follows.
```console
$ mysql -pPass@1234 -t gost
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 20
Server version: 8.0.27-0ubuntu0.20.04.1 (Ubuntu)
Copyright (c) 2000, 2021, Oracle and/or its …
```
> fix(rdb/ubuntu): change to db type: text

- cmd/microsoft.go
- db/db.go
- db/microsoft.go
- db/rdb.go
- db/redis.go
- fetcher/microsoft.go
- models/microsoft.go
- server/server.go
Change the search method from using only unapplied KBIDs to using both applied KBIDs and unapplied KBIDs.
This change will allow us to detect CVE-IDs that may exist between applied and unapplied KBIDs by considering the supersededby of each KBID.
```console
$ curl -H "Content-type: application/json" -X POST -d '{"applied": ["2079403"], "unapplied": ["2092914"]}' http://127.0.0.1:1325/microsoft/kbids | jq .
{
"2092914": [
"CVE-2010-1903",
"CVE-2010-1900",
"CVE-2010-1902",
"CVE-2010-1901"
],
"2431831": [
"CVE-2010-3946",
"CVE-2010-3947",
"CVE-2010-3952",
"CVE-2010-3949",
"CVE-2010-3951",
"CVE-2010-3950",
"CVE-2010-3945"
],
"2680317": [
"CVE-2012-0177"
],
"2719985": [
"CVE-2012-1889"
],
"2754670": [
"CVE-2012-2550"
],
"2757638": [
"CVE-2013-0007",
"CVE-2013-0006"
]
}
```
You don't have to …
> feat(ms): support KB Relation

- db/redis.go
- db/ubuntu.go
- go.sum
The Ubuntu Security Tracker includes data for Ubuntu ESM. 
This update enables Vuls to scan Ubuntu Linux versions even after their End of Life (EOL). 
Information pertaining to Ubuntu ESM is available in a specific format; by incorporating this data into our search parameters, we can detect Vulns of Ubuntu ESM.
https://ubuntu.com/security/esm
```
sqlite> select distinct release_name from ubuntu_release_patches where release_name like '%esm%' limit 1000;
esm-apps/bionic
esm-apps/focal
esm-apps/jammy
esm-apps/xenial
esm-infra/xenial
precise/esm
ros-esm/bionic
ros-esm/xenial
trusty/esm
```
```
./gost.new version     gost v0.4.3 6886bb9
./gost.old version       gost v0.4.3 8dc024f
```
make diff-server-rdb-redis
```
make diff-server-rdb-redis …
```
> feat(ubuntu): support Ubuntu ESM

- fetcher/redhatapi.go
- models/redhat.go
Fixes #194 
```console
$ gost fetch redhatapi
INFO[06-13|15:21:42] Initialize Database 
INFO[06-13|15:21:42] Fetch the list of CVEs 
INFO[06-13|15:24:22] Fetched 28436 CVEs 
28436 / 28436 [-------------------------------------------------] 100.00% 20 p/s
Failed to fetch the CVE details. err: json: cannot unmarshal object into Go struct field RedhatCVEJSON.mitigation of type string
```
```console
$ gost fetch redhatapi
INFO[06-14|00:39:48] Initialize Database 
INFO[06-14|00:39:48] Fetch the list of CVEs 
INFO[06-14|00:42:23] Fetched 28441 CVEs 
28441 / 28441 [-------------------------------------------------] 100.00% 17 p/s
INFO[06-14|01:09:36] Insert RedHat into DB                    db=sqlite3
INFO[06-14|01:09:36] Insert 28441 CVEs 
28441 / 28441 …
```
> fix(fetcher/redhatapi): mitigation type switch

- fetcher/redhat.go
- fetcher/ubuntu.go
Fixes #93 
vuln-list was temporarily inaccessible.
And vuln-list, which has regained access, no longer has the redhat directory that was there before, and has moved to the api directory of the vuln-list-redhat repository.
```console
$ gost fetch redhat
gost fetch redhat
INFO[07-27|16:46:09] Initialize Database 
INFO[07-27|16:46:11] Insert RedHat into DB                    db=sqlite3
INFO[07-27|16:46:11] Insert 0 CVEs 
0 [___________________________________________________________________] ?% ? p/s
```
```console
$ gost fetch redhat
INFO[07-27|16:48:34] Initialize Database 
INFO[07-27|16:48:35] Insert RedHat into DB                    db=sqlite3
INFO[07-27|16:48:35] Insert 28699 CVEs 
28699 / 28699 [-----------------------------------------------] 100.00% 4383 p/s
```
You don't have to …
> fix(fetcher/redhat): use vuln-list-redhat insted of vuln-list

- fetcher/ubuntu.go
vuln-list repository has stopped updating as follows.
```console
$ git clone --depth 1 https://github.com/aquasecurity/vuln-list.git
Cloning into 'vuln-list'...
remote: Enumerating objects: 390383, done.
remote: Counting objects: 100% (390383/390383), done.
remote: Compressing objects: 100% (103538/103538), done.
remote: Total 390383 (delta 317891), reused 345568 (delta 279851), pack-reused 0
Receiving objects: 100% (390383/390383), 294.43 MiB | 10.93 MiB/s, done.
Resolving deltas: 100% (317891/317891), done.
Updating files: 100% (370720/370720), done.
$ cd vuln-list
$ git log
commit dbd91fb18af8d182f3828360f3328a6e92d3bd0e (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: GitHub Action <action@github.com>
Date:   Thu Jul 20 12:49:23 2023 +0000
OSV Database
```
Currently, they are …
> fix(fetcher/ubuntu): temporarily use vuln-list-reserve

- fetcher/ubuntu.go
vuln-list(https://github.com/aquasecurity/vuln-list) has been revived, and vuln-list-reserve(https://github.com/aquasecurity/vuln-list-reserve) has stopped updating.
Therefore, change the repository used for ubuntu fetch from vuln-list-reserve to vuln-list.
```console
$ gost fetch ubuntu
INFO[09-06|15:24:21] Initialize Database 
INFO[09-06|15:24:21] Fetched                                  CVEs=44821
INFO[09-06|15:24:21] Insert Ubuntu into DB                    db=sqlite3
44821 / 44821 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 532 p/s
```
```console
$ gost fetch ubuntu
INFO[09-06|15:17:20] Initialize Database 
INFO[09-06|15:17:20] Fetched …
```
> feat(fetcher/ubuntu): use vuln-list instead of vuln-list-reserve

- models/debian.go
When referring to the Description in Trivy, there are some that are very large in size. In that case, the text type will not fit, and you will need to use longtext. Therefore, remove the gorm tag.
```console
$ bbolt get trivy.db vulnerability CVE-2023-5090 | jq .Description > CVE-2023-5090_Description.txt
```
[CVE-2023-5090_Description.txt](https://github.com/vulsio/gost/files/13065340/CVE-2023-5090_Description.txt)
```console
$ docker run --rm --name mysql -d -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=test -p 3306:3306 mysql
$ gost fetch debian --dbtype mysql --dbpath "root:password@tcp(127.0.0.1:3306)/test?parseTime=true"
INFO[10-23|10:30:54] Initialize Database 
INFO[10-23|10:30:57] Fetched all CVEs from Debian 
INFO[10-23|10:31:12] Fetched …
```
> fix(models/debian): remove gorm tag for mysql

- git/git.go
gost doesn't work on macOS as git returns an unexpected output.
```
$ gost fetch ubuntu --dbtype redis --dbpath redis://localhost
Failed to initialize vulnerability DB . err: error in vulnsrc clone or pull: failed to clone repository: error in version.NewVersion(2.39.3 (Apple Git-145)): Malformed version: 2.39.3 (Apple Git-145)
```
Run gost in macOS.
> fix: parse the git output

- db/ubuntu.go
add ubuntu 24.04
```console
$ gost fetch ubuntu 
INFO[04-30|15:41:03] Initialize Database 
INFO[04-30|15:41:04] Fetched                                  CVEs=48077
INFO[04-30|15:41:04] Insert Ubuntu into DB                    db=sqlite3
48077 / 48077 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 490 p/s
$ sqlite3 gost.sqlite3 "SELECT EXISTS(SELECT * FROM ubuntu_release_patches WHERE release_name = 'noble')"
1
$ gost server
$ curl -s http://127.0.0.1:1325/ubuntu/2404/pkgs/linux/unfixed-cves | jq
{
"CVE-2013-7445": {
"public_date_at_usn": "1000-01-01T00:00:00Z",
"crd": "1000-01-01T00:00:00Z",
"candidate": "CVE-2013-7445",
"public_date": …
```
> feat(ubuntu): add 24.04 noble

- .github/workflows/fetch.yml
- cmd/arch.go
- db/arch.go
- db/db.go
- db/rdb.go
- db/redis.go
- fetcher/arch.go
- models/arch.go
- server/server.go
add arch
```console
$ gost fetch arch
$ gost server 
$ curl -s http://127.0.0.1:1325/arch/advs/AVG-1 | jq
{
"name": "AVG-1",
"packages": [
{
"name": "lib32-gdk-pixbuf2"
}
],
"status": "Fixed",
"severity": "Critical",
"type": "arbitrary code execution",
"affected": "2.34.0-1",
"fixed": "2.36.0+2+ga7c869a-1",
"ticket": null,
"issues": [
{
"issue": "CVE-2016-6352"
}
],
"advisories": [
{
"advisory": "ASA-201611-12"
}
]
}
$ curl -s http://127.0.0.1:1325/arch/pkgs/bzip2/fixed-advs | jq
{
"AVG-4": {
"name": "AVG-4",
"packages": [
{
"name": "bzip2"
}
],
"status": "Fixed",
"severity": "Low",
"type": "denial of service",
"affected": "1.0.6-5",
"fixed": "1.0.6-6",
"ticket": null,
"issues": [
{
"issue": "CVE-2016-3189"
} …
```
> feat(cmd): add arch

- models/microsoft.go
As shown below, if there are no revisions, the PublishDate and LastUpdateDate will be 0000-00-00. 
```console
$ curl -s https://raw.githubusercontent.com/vulsio/windows-vuln-feed/main/dist/vulnerability/vulnerability.json.gz | zcat | jq -r '.[] | select(.CVEID == "CVE-2022-28737")'
{
"CVEID": "CVE-2022-28737",
"Tag": "Mariner",
"CNA": "security@ubuntu.com",
"ExploitStatus": "DOS:N/A",
"Products": null,
"URL": "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-28737"
}
```
If you are using MySQL, this may fail.
https://github.com/vulsio/gost/actions/runs/10783604555/job/29905826463
In such cases, change them to use 1000-01-01 instead of 0000-00-00.
test …
> fix(models/microsoft): fill default time to PublishDate, LastUpdateDate

- db/arch.go
- db/db.go
- db/debian.go
- db/microsoft.go
- db/rdb.go
- db/redhat.go
- db/redis.go
- db/ubuntu.go
- go.mod
- models/debian.go
- models/microsoft.go
- util/util.go
Use slices and maps from the standard library instead of experimental slices and maps.
ci test
> refactor: use std slices, maps package

- cmd/ubuntu.go
- db/db.go
- db/redis.go
- db/ubuntu.go
- fetcher/ubuntu.go
- models/ubuntu.go
- util/util.go
Use iterator to improve memory usage.
Max RSS: 3.98GiB
```
Command being timed: "./gost fetch ubuntu"
User time (seconds): 217.06
System time (seconds): 24.51
Percent of CPU this job got: 96%
Elapsed (wall clock) time (h:mm:ss or m:ss): 4:10.60
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 4173456
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 4849
Minor (reclaiming a frame) page faults: 2797255
Voluntary context switches: 323585
Involuntary context switches: 1587913
Swaps: 0
File system inputs: 0
File system outputs: 0
Socket messages sent: 15
Socket messages received: 31
Signals delivered: 15960
Page size (bytes): 16384
Exit status: 0 …
```
> refactor(ubuntu): use iterator

- cmd/notify.go
- cmd/redhat.go
- cmd/redhatapi.go
- cmd/ubuntu.go
- db/db.go
- db/redhat.go
- db/redis.go
- db/ubuntu.go
- fetcher/redhat.go
- models/redhat.go
- models/ubuntu.go
- util/util.go
use iterator in fetching redhat
```console
$ /usr/bin/time -v ./gost fetch redhat
INFO[04-28|11:33:34] Initialize Database 
INFO[04-28|11:33:34] Insert RedHat into DB                    db=sqlite3
INFO[04-28|11:33:34] Insert 37983 CVEs 
37983 / 37983 [-------------------------------------------------------------------------------------] 100.00% 2270 p/s
Command being timed: "./gost fetch redhat"
User time (seconds): 54.15
System time (seconds): 13.87
Percent of CPU this job got: 22%
Elapsed (wall clock) time (h:mm:ss or m:ss): 5:06.05
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): …
```
> refactor(fetcher/redhat): use iterator

- db/debian.go
- fetcher/debian.go
This pull request add support for debian 14, fetcher is failling since debian 13 release this weekend (09th August 2025) and the addition of debian 14 (Forky) which is not supported by gost yet.
It failed with the following error:
```
/gost fetch  debian
`INFO[08-11|11:32:33] Initialize Database 
INFO[08-11|11:32:33] Fetched all CVEs from Debian 
Failed to fetch CVE details from Trivy-DB. err: Failed to view db. err: Failed to foreach. err: not found debian major version. actual: 14
```
Fixes #332 
by fetch CI (https://github.com/vulsio/gost/actions/runs/16947850895/job/48033312301?pr=333)
> feat(db,fetcher/debian): Add Debian 14 (forky) and 15 (duke)

- models/redhat.go
It seems that line breaks have been included in references from before. 
https://github.com/aquasecurity/vuln-list-redhat/blob/e680b6fad101e24090d5bed970f4176916a56f0f/api/2025/CVE-2025-47907.json
They will now be split appropriately using line breaks.
https://go.dev/play/p/TphzEksSyBZ
```console
$ gost fetch redhat
$ gost server &
$ curl -s http://127.0.0.1:1325/redhat/cves/CVE-2025-47907 | jq .References
[
{
"Reference": "https://www.cve.org/CVERecord?id=CVE-2025-47907\nhttps://nvd.nist.gov/vuln/detail/CVE-2025-47907\nhttps://go.dev/cl/693735\nhttps://go.dev/issue/74831\nhttps://groups.google.com/g/golang-announce/c/x5MKroML2yM\nhttps://pkg.go.dev/vuln/GO-2025-3849"
}
]
```
```console
$ gost fetch redhat
$ …
```
> fix(models/redhat): split reference with a newline
